/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package us.albertzb.tarot.ui;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.util.List;
import java.util.stream.IntStream;
import javax.swing.SwingUtilities;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.html.HTMLDocument;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import us.albertzb.tarot.model.TarotDeck;
import us.albertzb.tarot.spreads.Concern;
import us.albertzb.tarot.spreads.PastPresentFuture;
import us.albertzb.tarot.spreads.PracticalAdvice;
import us.albertzb.tarot.spreads.Spreadable;
import us.albertzb.tarot.utils.CardImageLoader;
import us.albertzb.tarot.utils.DeckStack;
import us.albertzb.tarot.utils.YamlReader;

/**
 *
 * @author albertzb [albertzb42@gmail.com]
 */
public class TarotTable extends javax.swing.JFrame {

    private static final Logger LOG = LoggerFactory.getLogger(TarotTable.class);
    private static final long serialVersionUID = 1L;
    private static final String CARDS_FILE = "cards/tarot/cards.yml";
    private static final String P_TEMPLATE = "<html><body><h1>%s</h1><p>%s</p><p id=\"foot\" /></body></html>";
    private static final String I_TEMPLATE = "<h2>%s</h2><p>%s</p>";
    private static final String I_WARNING = "Problem when writing interpretation";

    private transient final DeckStack stack;
    private transient Spreadable spread;
    private transient List<CardImage> images;

    /**
     * Creates new form TarotTable
     */
    public TarotTable() {
        initComponents();
        spreadPnl.setLayout(new CenterRowLayout(20));
        TarotDeck deck = readDeck();
        SwingUtilities.invokeLater(() -> {
            CardImageLoader imageLoader = new CardImageLoader(deck);
            imageLoader.load();
        });
        stack = new DeckStack(deck);
    }

    private void closeFrame() {
        LOG.info("Closing the table");
        SwingUtilities.invokeLater(() -> {
            this.dispose();
        });
    }

    private TarotDeck readDeck() {
        return YamlReader.read(CARDS_FILE);
    }

    private void prepareSpread(Spreadable spread) {
        this.spread = spread;
        images = stack.drawImages(spread.getCardCount());
        //show the image in the middle of the table
        spreadPnl.removeAll();
        for (CardImage image : images) {
            spreadPnl.add(image);
        }
        spreadPnl.revalidate();
        spreadPnl.repaint();

        interpretationPnl.setText(String.format(P_TEMPLATE, spread.getTitle(), spread.getSubTitle()));
        HTMLDocument doc = (HTMLDocument) interpretationPnl.getDocument();
        IntStream.range(0, spread.getPositionCount())
                .forEachOrdered(i -> {
                    Element footer = doc.getElement("foot");
                    String interpretation = String.format(I_TEMPLATE, spread.getPositions().get(i), images.get(i).getInterpretation());
                    try {
                        doc.insertBeforeStart(footer, interpretation);
                    } catch (IOException | BadLocationException ex) {
                        LOG.warn(I_WARNING, ex);
                    }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPnl = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        ppfBtn = new javax.swing.JButton();
        concernBtn = new javax.swing.JButton();
        practicalBtn = new javax.swing.JButton();
        copyBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        splitPnl = new javax.swing.JSplitPane();
        spreadPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        interpretationPnl = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Tarot Table");

        buttonPnl.setLayout(new javax.swing.BoxLayout(buttonPnl, javax.swing.BoxLayout.LINE_AXIS));
        buttonPnl.add(filler1);

        ppfBtn.setText("Past Present Future");
        ppfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppfBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(ppfBtn);

        concernBtn.setText("Concern");
        concernBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concernBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(concernBtn);

        practicalBtn.setText("Practical Advise");
        practicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practicalBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(practicalBtn);

        copyBtn.setText("Copy");
        copyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(copyBtn);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(closeBtn);

        getContentPane().add(buttonPnl, java.awt.BorderLayout.SOUTH);

        splitPnl.setResizeWeight(0.9);

        spreadPnl.setBackground(new java.awt.Color(51, 0, 51));
        spreadPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 15, 5));
        splitPnl.setLeftComponent(spreadPnl);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(115, 200));

        interpretationPnl.setEditable(false);
        interpretationPnl.setContentType("text/html"); // NOI18N
        interpretationPnl.setMinimumSize(new java.awt.Dimension(62, 200));
        interpretationPnl.setPreferredSize(new java.awt.Dimension(62, 200));
        jScrollPane1.setViewportView(interpretationPnl);

        splitPnl.setRightComponent(jScrollPane1);

        getContentPane().add(splitPnl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        closeFrame();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void practicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practicalBtnActionPerformed
        prepareSpread(new PracticalAdvice());
    }//GEN-LAST:event_practicalBtnActionPerformed

    private void ppfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppfBtnActionPerformed
        prepareSpread(new PastPresentFuture());
    }//GEN-LAST:event_ppfBtnActionPerformed

    private void concernBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concernBtnActionPerformed
        prepareSpread(new Concern());
    }//GEN-LAST:event_concernBtnActionPerformed

    private void copyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBtnActionPerformed
        if (spread == null) {
            return;
        }
        final StringBuilder sb = new StringBuilder(100);
        sb.append("#")
                .append(spread.getTitle())
                .append("\n\n")
                .append(spread.getSubTitle())
                .append("\n\n");

        IntStream.range(0, spread.getPositionCount())
                .forEachOrdered(i -> {
                    sb.append("##")
                            .append(spread.getPositions().get(i))
                            .append("\n\n")
                            .append(images.get(i).getInterpretation())
                            .append("\n\n");
                });

        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(new StringSelection(sb.toString()), null);
    }//GEN-LAST:event_copyBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPnl;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton concernBtn;
    private javax.swing.JButton copyBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JEditorPane interpretationPnl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ppfBtn;
    private javax.swing.JButton practicalBtn;
    private javax.swing.JSplitPane splitPnl;
    private javax.swing.JPanel spreadPnl;
    // End of variables declaration//GEN-END:variables
}
