/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package us.albertzb.tarot.ui;

import java.io.IOException;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.html.HTMLDocument;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import us.albertzb.tarot.model.TarotDeck;
import us.albertzb.tarot.spreads.Concern;
import us.albertzb.tarot.spreads.PastPresentFuture;
import us.albertzb.tarot.spreads.PracticalAdvice;
import us.albertzb.tarot.utils.CardImageLoader;
import us.albertzb.tarot.utils.DeckStack;
import us.albertzb.tarot.utils.YamlReader;

/**
 *
 * @author albertzb [albertzb42@gmail.com]
 */
public class TarotTable extends javax.swing.JFrame {

    private static final Logger LOG = LoggerFactory.getLogger(TarotTable.class);
    private static final long serialVersionUID = 1L;
    private static final String CARDS_FILE = "cards/tarot/cards.yml";

    private transient final TarotDeck deck;

    /**
     * Creates new form TarotTable
     */
    public TarotTable() {
        initComponents();
        deck = readDeck();
        SwingUtilities.invokeLater(() -> {
            CardImageLoader imageLoader = new CardImageLoader(deck);
            imageLoader.load();
        });
    }

    private void closeFrame() {
        LOG.info("Closing the table");
        SwingUtilities.invokeLater(() -> {
            this.dispose();
        });
    }

    private TarotDeck readDeck() {
        return YamlReader.read(CARDS_FILE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPnl = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        ppfBtn = new javax.swing.JButton();
        concernBtn = new javax.swing.JButton();
        practicalBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        splitPnl = new javax.swing.JSplitPane();
        layoutPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        interpretationPnl = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Tarot Table");

        buttonPnl.setLayout(new javax.swing.BoxLayout(buttonPnl, javax.swing.BoxLayout.LINE_AXIS));
        buttonPnl.add(filler1);

        ppfBtn.setText("Past Present Future");
        ppfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppfBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(ppfBtn);

        concernBtn.setText("Concern");
        concernBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concernBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(concernBtn);

        practicalBtn.setText("Practical Advise");
        practicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practicalBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(practicalBtn);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        buttonPnl.add(closeBtn);

        getContentPane().add(buttonPnl, java.awt.BorderLayout.SOUTH);

        splitPnl.setResizeWeight(0.9);

        layoutPnl.setBackground(new java.awt.Color(51, 0, 51));
        layoutPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 15, 5));
        splitPnl.setLeftComponent(layoutPnl);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(115, 200));

        interpretationPnl.setEditable(false);
        interpretationPnl.setContentType("text/html"); // NOI18N
        interpretationPnl.setMinimumSize(new java.awt.Dimension(62, 200));
        interpretationPnl.setPreferredSize(new java.awt.Dimension(62, 200));
        jScrollPane1.setViewportView(interpretationPnl);

        splitPnl.setRightComponent(jScrollPane1);

        getContentPane().add(splitPnl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        closeFrame();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void practicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practicalBtnActionPerformed
        //shuffle the cards and take the first card
        DeckStack stack = new DeckStack(deck);
        List<CardImage> images = stack.drawImages(PracticalAdvice.cardCount);
        //show the image in the middle of the table
        layoutPnl.removeAll();
        for (CardImage image : images) {
            layoutPnl.add(image);
        }
        layoutPnl.revalidate();
        layoutPnl.repaint();

        interpretationPnl.setText("<html><body><h1>Practical advice</h1><p>This may help</p><p id=\"foot\" /></body></html>");
        HTMLDocument doc = (HTMLDocument) interpretationPnl.getDocument();
        for (PracticalAdvice.Position position : PracticalAdvice.Position.values()) {
            Element footer = doc.getElement("foot");
            String interpretation = String.format("<h2>%s</h2><p>%s</p>", position.getTitle(), images.get(position.getIndex()).getInterpretation());
            try {
                doc.insertBeforeStart(footer, interpretation);
            } catch (IOException | BadLocationException ex) {
                LOG.warn("Problem when writing interpretation", ex);
            }
        }
    }//GEN-LAST:event_practicalBtnActionPerformed

    private void ppfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppfBtnActionPerformed
        //shuffle the cards and take the first card
        DeckStack stack = new DeckStack(deck);
        List<CardImage> images = stack.drawImages(PastPresentFuture.cardCount);
        //show the image in the middle of the table
        layoutPnl.removeAll();
        for (CardImage image : images) {
            layoutPnl.add(image);
        }
        layoutPnl.revalidate();
        layoutPnl.repaint();

        interpretationPnl.setText("<html><body><h1>Past-Present-Future</h1><p>This is how the cards see your situation</p><p id=\"foot\" /></body></html>");
        HTMLDocument doc = (HTMLDocument) interpretationPnl.getDocument();
        for (PastPresentFuture.Position position : PastPresentFuture.Position.values()) {
            Element footer = doc.getElement("foot");
            String interpretation = String.format("<h2>%s</h2><p>%s</p>", position.getTitle(), images.get(position.getIndex()).getInterpretation());
            try {
                doc.insertBeforeStart(footer, interpretation);
            } catch (IOException | BadLocationException ex) {
                LOG.warn("Problem when writing interpretation", ex);
            }
        }
    }//GEN-LAST:event_ppfBtnActionPerformed

    private void concernBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concernBtnActionPerformed
                //shuffle the cards and take the first card
        DeckStack stack = new DeckStack(deck);
        List<CardImage> images = stack.drawImages(Concern.cardCount);
        //show the image in the middle of the table
        layoutPnl.removeAll();
        for (CardImage image : images) {
            layoutPnl.add(image);
        }
        layoutPnl.revalidate();
        layoutPnl.repaint();

        interpretationPnl.setText("<html><body><h1>Dealing with your Concern</h1><p>Maybe you can cope this way</p><p id=\"foot\" /></body></html>");
        HTMLDocument doc = (HTMLDocument) interpretationPnl.getDocument();
        for (Concern.Position position : Concern.Position.values()) {
            Element footer = doc.getElement("foot");
            String interpretation = String.format("<h2>%s</h2><p>%s</p>", position.getTitle(), images.get(position.getIndex()).getInterpretation());
            try {
                doc.insertBeforeStart(footer, interpretation);
            } catch (IOException | BadLocationException ex) {
                LOG.warn("Problem when writing interpretation", ex);
            }
        }
    }//GEN-LAST:event_concernBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPnl;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton concernBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JEditorPane interpretationPnl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel layoutPnl;
    private javax.swing.JButton ppfBtn;
    private javax.swing.JButton practicalBtn;
    private javax.swing.JSplitPane splitPnl;
    // End of variables declaration//GEN-END:variables
}
